version: "2"

run:
  timeout: 5m

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - unused
    - bodyclose
    - importas
    - dogsled
    - dupl
    - gochecknoinits
    - gocognit
    - gocritic
    - gocyclo
    - misspell
    - nakedret
    - prealloc
    - unconvert
    - whitespace
    - rowserrcheck
    - goconst
    - asciicheck
    - nestif
    - sqlclosecheck
