version: "2"

run:
  deadline: 5m
  issues-exit-code: 1

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - unused
    - bodyclose
    - importas
    - dogsled
    - dupl
    - gochecknoinits
    - gocognit
    - gocritic
    - gocyclo
    - misspell
    - nakedret
    - prealloc
    - unconvert
    - whitespace
    - rowserrcheck
    - goconst
    - asciicheck
    - nestif
    - sqlclosecheck

linters-settings:
  govet:
    check-shadowing: true
  goimports:
    local-prefixes: bkit
  gocritic:
    disabled-checks:
      - sloppyReassign
      - whyNoLint
    enabled-tags:
      - experimental
      - opinionated
  wrapcheck:
    ignorePackageGlobs:
      - bkit/*
